export const EXPERIENCE_CHANNELS = [
  {
    title: "实战教程",
    description: "从任务背景、工具选择、操作过程到输出结果，沉淀可复用做法。",
    count: 12,
  },
  {
    title: "避坑反馈",
    description: "记录免费额度、导出限制、模型幻觉、协作成本和真实使用边界。",
    count: 8,
  },
  {
    title: "工具组合",
    description: "围绕一个工作任务，把多个工具串成可执行流程。",
    count: 6,
  },
  {
    title: "福利线索",
    description: "补充限时试用、开发者额度、教育优惠和领取路径。",
    count: 5,
  },
] as const;

export const EXPERIENCE_POSTS = [
  {
    id: "chatgpt-gamma-prd-report",
    title: "用 ChatGPT 先拆 PRD，再让 Gamma 生成汇报初稿",
    channel: "实战教程",
    scenario: "文档写作",
    tools: ["ChatGPT", "Gamma"],
    roles: ["产品", "运营"],
    author: "星点评编辑部",
    summary: "先把客户访谈拆成目标、限制和验收点，再把结构化内容交给演示工具生成可评审版本。",
    publishedAt: "2026-05-08",
    views: 128,
    likes: 34,
    favorites: 17,
    isOfficial: true,
    takeaways: ["先把访谈材料拆成目标、限制和验收点", "让 ChatGPT 输出可直接给 Gamma 使用的汇报结构", "人工复核客户原话和关键数据后再交付"],
    steps: ["整理客户访谈和背景材料，删掉和汇报无关的闲聊内容。", "要求 ChatGPT 按目标、受众、约束、验收标准拆解 PRD 信息。", "把结构化大纲交给 Gamma 生成初稿，再人工调整案例页和结论页。"],
    pitfalls: ["不要把未确认的客户指标直接写进提示词，否则 Gamma 会把它包装成结论。", "不要让演示工具一次性生成最终版，先生成评审稿更容易控制方向。"],
  },
  {
    id: "cursor-frontend-error-fix",
    title: "Cursor 定位前端报错时，不要让它顺手重构全项目",
    channel: "避坑反馈",
    scenario: "代码开发",
    tools: ["Cursor"],
    roles: ["前端", "全栈"],
    author: "全栈研发用户",
    summary: "把报错栈、接口返回和组件边界一次给清楚，要求只找最小修改点，最后用测试固定结果。",
    publishedAt: "2026-05-06",
    views: 96,
    likes: 28,
    favorites: 12,
    isOfficial: false,
    takeaways: ["把报错栈、接口返回和复现步骤一次给清楚", "限定 Cursor 只找最小修改点", "修复后用测试固定边界"],
    steps: ["复制浏览器 console、终端报错和相关组件路径。", "要求 Cursor 先解释根因，再列出不超过两个修改点。", "应用补丁后只跑相关测试，确认没有顺手重构。"],
    pitfalls: ["不要直接说“帮我修一下”，它容易扩大改动范围。", "不要忽略测试输出里的历史 warning，要区分 warning 和新失败。"],
  },
  {
    id: "presales-ai-proposal",
    title: "售前方案半天出稿：客户背景、痛点和案例怎么喂给 AI",
    channel: "工具组合",
    scenario: "客户方案",
    tools: ["Claude", "Gamma", "Canva AI"],
    roles: ["售前", "商务"],
    author: "售前顾问",
    summary: "先用长文本模型归纳客户材料，再用 PPT 工具生成骨架，最后用设计工具统一关键页面。",
    publishedAt: "2026-05-10",
    views: 142,
    likes: 45,
    favorites: 21,
    isOfficial: false,
    takeaways: ["长文本模型负责信息归纳，PPT 工具负责结构初稿", "客户行业案例要单独给，不要混在背景里", "最后一轮重点改标题和证据链"],
    steps: ["把客户背景、痛点、预算和决策链整理成一页材料。", "用 Claude 归纳出方案主线、反对意见和案例需求。", "交给 Gamma 生成汇报骨架，再用 Canva AI 统一关键视觉页。"],
    pitfalls: ["不要让 PPT 工具自由编案例，案例来源要可追溯。", "不要一开始追求版式精美，先让逻辑被客户看懂。"],
  },
  {
    id: "shuxuan-data-analysis",
    title: "星启·数璇做周报数据分析：从粘贴表格到生成洞察只用三步",
    channel: "实战教程",
    scenario: "数据分析",
    tools: ["星启·数璇"],
    roles: ["运营", "数据分析师"],
    author: "运营数据岗用户",
    summary: "把原始表格直接粘进对话框，先让模型识别字段和异常值，再要求按业务维度归因，最后导出结构化结论。",
    publishedAt: "2026-05-11",
    views: 87,
    likes: 22,
    favorites: 9,
    isOfficial: false,
    takeaways: ["先让工具识别字段含义，再做业务归因", "异常值要单独标注，不要直接丢进趋势判断", "结论最好导出成可复用的周报结构"],
    steps: ["粘贴原始表格并要求识别字段、时间范围和异常值。", "按业务维度提问，让模型输出趋势、异常和可能原因。", "把结论整理成周报段落和后续动作清单。"],
    pitfalls: ["不要省略字段解释，否则模型会误判业务口径。", "不要只看自动图表，关键指标仍要抽样核对。"],
  },
  {
    id: "chatgpt-canva-content",
    title: "ChatGPT 写脚本 + Canva 出图：短视频内容批量生产流程",
    channel: "工具组合",
    scenario: "内容生产",
    tools: ["ChatGPT", "Canva"],
    roles: ["内容运营", "新媒体"],
    author: "短视频内容创作者",
    summary: "用 ChatGPT 按选题批量生成脚本和分镜文字稿，再用 Canva 模板快速套出封面和关键帧，一套流程日产十条素材。",
    publishedAt: "2026-05-12",
    views: 203,
    likes: 58,
    favorites: 31,
    isOfficial: false,
    takeaways: ["脚本、分镜和封面文案要分批生成", "Canva 模板适合批量生产，不适合决定内容策略", "每个平台标题需要单独改写"],
    steps: ["用 ChatGPT 按选题批量生成脚本和镜头说明。", "把封面标题、关键帧文案和配图要求整理成表格。", "在 Canva 里套用模板，统一字体、封面和导出尺寸。"],
    pitfalls: ["不要让一条提示词同时生成十个平台版本。", "不要直接套模板发布，封面层级和品牌露出要人工检查。"],
  },
  {
    id: "kimi-mita-competitor-research",
    title: "Kimi 读招股书 + 秘塔 AI 搜索补盲区：竞品调研实操复盘",
    channel: "工具组合",
    scenario: "竞品调研",
    tools: ["Kimi", "秘塔AI搜索"],
    roles: ["产品", "战略分析"],
    author: "产品经理",
    summary: "先把竞品招股书和产品文档扔给 Kimi 做长文摘要和差异点提取，再用秘塔搜索补齐公开数据和行业报告，两小时出完整竞品分析。",
    publishedAt: "2026-05-13",
    views: 156,
    likes: 41,
    favorites: 19,
    isOfficial: false,
    takeaways: ["Kimi 适合长文档抽取，秘塔适合补公开来源", "竞品结论要按功能、定价、客户和风险分层", "引用来源要保留链接，方便复核"],
    steps: ["把招股书、产品文档和公开介绍交给 Kimi 做结构化摘要。", "用秘塔 AI 搜索补齐行业报告、新闻和用户评价。", "把差异点整理成功能对比表和风险判断。"],
    pitfalls: ["不要只依赖单个模型的摘要，关键数字必须回到原文。", "不要把搜索结果当事实，优先保留官方和报告来源。"],
  },
] as const;

export function getPostById(id: string): (typeof EXPERIENCE_POSTS)[number] | undefined {
  return EXPERIENCE_POSTS.find((post) => post.id === id);
}
