from __future__ import annotations

from datetime import date

from app.schemas.catalog import CategorySummary, ScenarioSummary
from app.schemas.tool import ToolDetail, ToolMediaItem, ToolSummary


def build_minimal_tool_summary(slug: str) -> ToolSummary:
    for tool in TOOLS:
        if tool.slug == slug:
            return ToolSummary(
                id=tool.id,
                slug=tool.slug,
                name=tool.name,
                category=tool.category,
                categorySlug=tool.categorySlug,
                score=tool.score,
                summary=tool.summary,
                tags=tool.tags,
                officialUrl=tool.officialUrl,
                logoPath=tool.logoPath,
                logoStatus=tool.logoStatus,
                logoSource=tool.logoSource,
                status=tool.status,
                featured=tool.featured,
                createdAt=tool.createdAt,
                price=tool.price,
                reviewCount=tool.reviewCount,
                accessFlags=tool.accessFlags,
                pricingType=tool.pricingType,
                priceMinCny=tool.priceMinCny,
                priceMaxCny=tool.priceMaxCny,
                freeAllowanceText=tool.freeAllowanceText,
                features=tool.features,
                limitations=tool.limitations,
                bestFor=tool.bestFor,
                dealSummary=tool.dealSummary,
                primaryMedia=tool.primaryMedia,
            )

    return ToolSummary(
        id=0,
        slug=slug,
        name=slug,
        category="暂未归类",
        score=0.0,
        summary="",
        tags=[],
        officialUrl="",
        status="published",
        featured=False,
        createdAt=date(2026, 1, 1),
    )


def _tool(
    *,
    id: int,
    slug: str,
    name: str,
    category: str,
    category_slug: str,
    score: float,
    summary: str,
    description: str,
    tags: list[str],
    features: list[str],
    limitations: list[str],
    best_for: list[str],
    deal_summary: str,
    official_url: str,
    pricing_type: str = "freemium",
    price: str = "免费增值",
    price_min: int | None = None,
    price_max: int | None = None,
    needs_vpn: bool | None = False,
    cn_lang: bool | None = True,
    cn_payment: bool | None = True,
    featured: bool = True,
    media_url: str | None = None,
) -> ToolDetail:
    media_items = [
        ToolMediaItem(type="image", url=media_url, title=f"{name} 产品演示", sourceName="官方")
    ] if media_url else []
    return ToolDetail(
        id=id,
        slug=slug,
        name=name,
        category=category,
        categorySlug=category_slug,
        score=score,
        summary=summary,
        tags=tags,
        officialUrl=official_url,
        logoPath=f"/logos/{slug}.png",
        logoStatus="matched",
        logoSource="seed",
        status="published",
        featured=featured,
        createdAt=date(2026, 4, 1),
        price=price,
        reviewCount=8 + id,
        accessFlags={"needsVpn": needs_vpn, "cnLang": cn_lang, "cnPayment": cn_payment},
        pricingType=pricing_type,
        priceMinCny=price_min,
        priceMaxCny=price_max,
        freeAllowanceText=deal_summary,
        features=features,
        limitations=limitations,
        bestFor=best_for,
        dealSummary=deal_summary,
        primaryMedia=media_items[0] if media_items else None,
        description=description,
        editorComment=f"{name} 的演示数据来自 seed，适合用于 Demo 环境快速核验产品定位。",
        developer="官方团队",
        country="",
        city="",
        platforms="Web",
        vpnRequired="需要" if needs_vpn else "不需要",
        targetAudience=best_for,
        abilities=features,
        pros=features[:2],
        cons=limitations[:2],
        pitfalls=limitations,
        scenarios=tags[:3],
        mediaItems=media_items,
        alternatives=[],
        lastVerifiedAt=date(2026, 4, 20),
    )


CATEGORIES: list[CategorySummary] = [
    CategorySummary(slug="general-assistants", name="通用助手", description="问答、写作、总结、研究和多任务协作。"),
    CategorySummary(slug="writing-office", name="写作办公", description="论文、文档、PPT、会议纪要和团队协作。"),
    CategorySummary(slug="coding-dev", name="编程开发", description="代码生成、debug、测试、接口和工程提效。"),
    CategorySummary(slug="design-media", name="图片视频", description="绘图、海报、修图、视频生成和创意素材。"),
    CategorySummary(slug="data-analysis", name="数据分析", description="BI、SQL、报表、仪表盘和可视化分析。"),
    CategorySummary(slug="agent-platform", name="Agent 平台", description="智能体、插件、知识库和工作流自动化。"),
]


TOOLS: list[ToolDetail] = [
    _tool(
        id=1,
        slug="chatgpt",
        name="ChatGPT",
        category="通用助手",
        category_slug="general-assistants",
        score=9.6,
        summary="通用 AI 助手，适合写论文、总结资料、代码解释和多轮协作。",
        description="适合把零散想法变成提纲、初稿或分析框架，但正式引用和关键事实需要人工核验。",
        tags=["写论文", "总结", "代码", "中文写作"],
        features=["中文写作和资料总结稳定", "覆盖问答、代码、表格和多模态任务", "生态和教程资料丰富"],
        limitations=["正式论文引用需要人工核验", "高阶模型和长上下文能力通常需要付费"],
        best_for=["学生", "研究人员", "内容团队", "产品经理"],
        deal_summary="免费版可用于基础问答和轻量写作，高阶能力需订阅。",
        official_url="https://chat.openai.com",
        price_min=0,
        price_max=145,
    ),
    _tool(
        id=2,
        slug="claude",
        name="Claude",
        category="通用助手",
        category_slug="general-assistants",
        score=9.4,
        summary="长文理解和结构化表达能力强，适合专业写作、资料分析和方案整理。",
        description="适合处理长文档、合同初读和专业写作，但访问门槛和中文生态需要单独评估。",
        tags=["长文写作", "学术", "文档", "总结"],
        features=["长上下文理解稳定", "适合专业写作和复杂文本分析", "表达自然"],
        limitations=["访问门槛较高", "部分高级能力需要订阅"],
        best_for=["研究人员", "咨询顾问", "内容团队"],
        deal_summary="免费额度有限，重度长文处理通常需要订阅。",
        official_url="https://claude.ai",
        pricing_type="freemium",
        price_min=0,
        price_max=145,
        needs_vpn=True,
        cn_lang=False,
        cn_payment=False,
    ),
    _tool(
        id=3,
        slug="deepseek",
        name="DeepSeek",
        category="通用助手",
        category_slug="general-assistants",
        score=9.2,
        summary="中文和代码场景性价比突出，适合国内团队快速试用。",
        description="适合中文问答、代码解释和低成本试错，复杂任务仍需看具体模型稳定性。",
        tags=["中文", "写代码", "免费", "国内可用"],
        features=["中文理解成本低", "代码解释和推理能力强", "国内访问门槛较低"],
        limitations=["不同入口的模型能力和限额不完全一致", "复杂生产任务仍需要复核"],
        best_for=["国内团队", "开发者", "学生"],
        deal_summary="有免费或低成本额度，适合先验证需求。",
        official_url="https://www.deepseek.com",
        pricing_type="freemium",
        price_min=0,
        price_max=99,
    ),
    _tool(
        id=4,
        slug="gamma",
        name="Gamma",
        category="写作办公",
        category_slug="writing-office",
        score=9.0,
        summary="AI PPT 和演示文稿生成工具，适合快速做汇报、答辩和路演初稿。",
        description="从主题到页面结构的生成速度很快，适合先出完整稿再人工精修。",
        tags=["PPT", "演示", "幻灯片", "汇报"],
        features=["快速生成 PPT 初稿", "能自动组织演示结构", "页面视觉完成度较高"],
        limitations=["高级导出和品牌模板需要付费", "中文细节和复杂排版仍需人工调整"],
        best_for=["产品经理", "销售", "学生答辩", "创业团队"],
        deal_summary="免费版可生成基础演示文稿，高级导出需升级。",
        official_url="https://gamma.app",
        price_min=0,
        price_max=79,
        needs_vpn=True,
        cn_lang=False,
        cn_payment=False,
    ),
    _tool(
        id=5,
        slug="canva-ai",
        name="Canva AI",
        category="图片视频",
        category_slug="design-media",
        score=8.7,
        summary="模板和轻设计能力成熟，适合海报、封面、PPT 和社媒素材。",
        description="适合没有专业设计资源的团队快速产出第一版视觉素材。",
        tags=["海报", "PPT", "设计", "图片"],
        features=["模板库丰富", "适合非设计岗位上手", "支持轻量图片和演示制作"],
        limitations=["创意上限依赖模板", "品牌一致性仍需人工把关"],
        best_for=["运营团队", "市场团队", "创业团队"],
        deal_summary="免费版可用，部分模板和素材需要 Pro。",
        official_url="https://www.canva.com",
        price_min=0,
        price_max=80,
    ),
    _tool(
        id=6,
        slug="cursor",
        name="Cursor",
        category="编程开发",
        category_slug="coding-dev",
        score=9.3,
        summary="AI 原生代码编辑器，适合写代码、debug、测试和重构。",
        description="把 AI 放进 IDE 工作流，适合真实项目里连续改代码。",
        tags=["写代码", "debug", "测试", "前端"],
        features=["可理解项目上下文", "适合代码重构和 bug 修复", "交互贴近开发流程"],
        limitations=["复杂仓库仍需要人工 review", "团队落地需要统一规范和权限边界"],
        best_for=["开发者", "技术团队", "独立开发者"],
        deal_summary="提供试用额度，重度使用需要订阅。",
        official_url="https://cursor.com",
        price_min=0,
        price_max=145,
        needs_vpn=True,
        cn_lang=False,
        cn_payment=False,
    ),
    _tool(
        id=7,
        slug="midjourney",
        name="Midjourney",
        category="图片视频",
        category_slug="design-media",
        score=9.2,
        summary="高质量图片生成工具，适合海报、封面和创意视觉探索。",
        description="视觉质感突出，但文字、精确排版和流程门槛仍是常见限制。",
        tags=["生成图片", "绘图", "海报", "封面"],
        features=["视觉质量高", "风格探索能力强", "适合概念图和灵感图"],
        limitations=["中文文字和精确排版需要后期处理", "主要为付费订阅"],
        best_for=["设计师", "内容创作者", "品牌团队"],
        deal_summary="主要为付费订阅，适合明确有图像产出需求的团队。",
        official_url="https://www.midjourney.com",
        pricing_type="subscription",
        price="订阅",
        price_min=72,
        price_max=430,
        needs_vpn=True,
        cn_lang=False,
        cn_payment=False,
    ),
    _tool(
        id=9,
        slug="coze",
        name="扣子 Coze",
        category="Agent 平台",
        category_slug="agent-platform",
        score=8.9,
        summary="适合快速搭建智能体、知识库和工作流，国内团队上手门槛低。",
        description="适合先做业务智能体验证，复杂系统集成仍要看平台约束。",
        tags=["Agent", "智能体", "工作流", "国内可用"],
        features=["国内访问更稳定", "智能体搭建快", "适合业务试点"],
        limitations=["复杂定制受平台能力约束", "深度私有化需要另行评估"],
        best_for=["运营团队", "产品团队", "企业数字化团队"],
        deal_summary="提供免费额度，适合先验证客服、内部助手和流程自动化。",
        official_url="https://www.coze.cn",
        price_min=0,
        price_max=199,
    ),
    _tool(
        id=10,
        slug="dify",
        name="Dify",
        category="Agent 平台",
        category_slug="agent-platform",
        score=8.7,
        summary="开源 LLM 应用平台，适合有研发能力的团队做私有化和编排。",
        description="在可控、扩展和部署弹性之间比较均衡，运维成本需要提前考虑。",
        tags=["Agent", "工作流", "开源", "知识库"],
        features=["开源可控", "支持工作流和知识库", "适合持续迭代 AI 应用"],
        limitations=["需要研发和运维支持", "配置复杂度高于托管平台"],
        best_for=["技术团队", "AI 产品团队", "企业研发"],
        deal_summary="开源版可自部署，商业版按需求评估。",
        official_url="https://dify.ai",
        pricing_type="freemium",
        price_min=0,
        price_max=None,
    ),
]


SCENARIOS: list[ScenarioSummary] = [
    ScenarioSummary(
        id=1,
        slug="ppt",
        title="做 PPT 用什么 AI",
        description="优先看能快速产出完整演示稿的工具，避免从空白页开始。",
        problem="汇报、答辩和提案常常时间紧，需要先拿到结构完整的第一版。",
        toolCount=3,
        primaryTools=[build_minimal_tool_summary("gamma"), build_minimal_tool_summary("canva-ai")],
        alternativeTools=[build_minimal_tool_summary("chatgpt")],
        targetAudience=["销售", "产品经理", "学生答辩"],
    ),
    ScenarioSummary(
        id=2,
        slug="writing",
        title="写论文和文档用什么 AI",
        description="适合先出结构、再润色成稿的内容工作流。",
        problem="关键不是替代判断，而是快速整理资料、形成提纲并暴露需要核验的位置。",
        toolCount=3,
        primaryTools=[build_minimal_tool_summary("chatgpt"), build_minimal_tool_summary("deepseek")],
        alternativeTools=[build_minimal_tool_summary("gamma")],
        targetAudience=["学生", "研究人员", "内容团队"],
    ),
]

RANKINGS = [
    {
        "slug": "hot",
        "title": "热门工具榜",
        "description": "优先展示综合热度、适用面和演示稳定性更高的工具。",
        "tool_slugs": ["chatgpt", "deepseek", "gamma", "cursor", "coze"],
    },
    {
        "slug": "demo",
        "title": "Demo 推荐榜",
        "description": "覆盖写论文、做 PPT、写代码、生成图片、数据分析和 Agent 场景。",
        "tool_slugs": ["chatgpt", "gamma", "cursor", "midjourney", "coze"],
    },
]
