"""add_fk_indexes"""

revision = '7127501bcdf6'
down_revision = '20260331_0003'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crawl_snapshots_crawl_job_id'), 'crawl_snapshots', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_ranking_items_ranking_id'), 'ranking_items', ['ranking_id'], unique=False)
    op.create_index(op.f('ix_ranking_items_tool_id'), 'ranking_items', ['tool_id'], unique=False)
    op.create_index(op.f('ix_scenario_tools_scenario_id'), 'scenario_tools', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_tools_tool_id'), 'scenario_tools', ['tool_id'], unique=False)
    op.create_index(op.f('ix_sources_tool_id'), 'sources', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_categories_category_id'), 'tool_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_tool_categories_tool_id'), 'tool_categories', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_tags_tag_id'), 'tool_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_tool_tags_tool_id'), 'tool_tags', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_updates_tool_id'), 'tool_updates', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_updates_tool_id'), table_name='tool_updates')
    op.drop_index(op.f('ix_tool_tags_tool_id'), table_name='tool_tags')
    op.drop_index(op.f('ix_tool_tags_tag_id'), table_name='tool_tags')
    op.drop_index(op.f('ix_tool_categories_tool_id'), table_name='tool_categories')
    op.drop_index(op.f('ix_tool_categories_category_id'), table_name='tool_categories')
    op.drop_index(op.f('ix_sources_tool_id'), table_name='sources')
    op.drop_index(op.f('ix_scenario_tools_tool_id'), table_name='scenario_tools')
    op.drop_index(op.f('ix_scenario_tools_scenario_id'), table_name='scenario_tools')
    op.drop_index(op.f('ix_ranking_items_tool_id'), table_name='ranking_items')
    op.drop_index(op.f('ix_ranking_items_ranking_id'), table_name='ranking_items')
    op.drop_index(op.f('ix_crawl_snapshots_crawl_job_id'), table_name='crawl_snapshots')
    # ### end Alembic commands ###
